### ISSUE TITLE
Dto의 명명 규칙 확인 부탁드립니다.

### ISSUE THREAD

**Issue by JANG-WON-JUN** [SP0F0/spofo-portfolio#14]
StockDto, CreatePortfolio 클래스는 request dto의 역할을 담당하고 있는데 명명 규칙이 통일 되지 않고 있습니다.

**Comment by gayeonP** [comment]
* {블라블라}request
* {블라블라}response
* Dto는 생략

명명 규칙 통일하기로 했습니다.
